development:
  adapter: postgresql
  encoding: unicode
  database: user_development
  pool: 5
  username: rails
  password: rails

test:
  adapter: postgresql
  encoding: unicode
  database: user_test
  pool: 5
  username: rails
  password: rails
